#!/bin/sh
# Writes deploy overrides to stdout. Used by GitHub Actions CD.
# Required env: DOCKERHUB_USERNAME, IMAGE_TAG, API_HOST, USER_APP_HOST, ADMIN_APP_HOST,
# JWT_ACCESS_SECRET, JWT_RESET_SECRET, POSTGRES_USER, POSTGRES_PASSWORD,
# MONGO_ROOT_USER, MONGO_ROOT_PASSWORD, FRONTEND_ORIGIN, FRONTEND_URL, OPENAI_API_KEY
# Optional env: OAUTH_*, GOOGLE_*, GITHUB_*, VIDEOSDK_*, EMAIL_*, CLOUDINARY_*, K8S_NAMESPACE

set -eu

NS="${K8S_NAMESPACE:-navi}"
PU="${POSTGRES_USER:?POSTGRES_USER required}"
PP="${POSTGRES_PASSWORD:?POSTGRES_PASSWORD required}"
MU="${MONGO_ROOT_USER:?MONGO_ROOT_USER required}"
MP="${MONGO_ROOT_PASSWORD:?MONGO_ROOT_PASSWORD required}"

cat <<EOF
namespace: ${NS}
image:
  registry: ${DOCKERHUB_USERNAME:?DOCKERHUB_USERNAME required}
  tag: ${IMAGE_TAG:-latest}
ingress:
  apiHost: ${API_HOST:?API_HOST required}
  userAppHost: ${USER_APP_HOST:?USER_APP_HOST required}
  adminAppHost: ${ADMIN_APP_HOST:?ADMIN_APP_HOST required}
secrets:
  JWT_ACCESS_SECRET: "${JWT_ACCESS_SECRET:?JWT_ACCESS_SECRET required}"
  JWT_RESET_SECRET: "${JWT_RESET_SECRET:?JWT_RESET_SECRET required}"
  POSTGRES_USER: "${PU}"
  POSTGRES_PASSWORD: "${PP}"
  MONGO_ROOT_USER: "${MU}"
  MONGO_ROOT_PASSWORD: "${MP}"
  AUTH_DATABASE_URL: "postgresql://${PU}:${PP}@postgres:5432/auth_db"
  USER_DATABASE_URL: "postgresql://${PU}:${PP}@postgres:5432/user_db"
  CHAT_DB: "mongodb://${MU}:${MP}@mongo:27017/chat_db?authSource=admin"
  NETWORK_DB_URL: "mongodb://${MU}:${MP}@mongo:27017/network_db?authSource=admin"
  NOTIFICATION_DB_URL: "mongodb://${MU}:${MP}@mongo:27017/notification_db?authSource=admin"
  FRONTEND_ORIGIN: "${FRONTEND_ORIGIN:-}"
  OAUTH_FRONTEND_LOGIN_URL: "${OAUTH_FRONTEND_LOGIN_URL:-}"
  OAUTH_FRONTEND_REDIRECT_URL: "${OAUTH_FRONTEND_REDIRECT_URL:-}"
  GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID:-}"
  GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET:-}"
  GOOGLE_CALLBACK_URL: "${GOOGLE_CALLBACK_URL:-}"
  GITHUB_CLIENT_ID: "${GITHUB_CLIENT_ID:-}"
  GITHUB_CLIENT_SECRET: "${GITHUB_CLIENT_SECRET:-}"
  GITHUB_CALLBACK_URL: "${GITHUB_CALLBACK_URL:-}"
  VIDEOSDK_API_KEY: "${VIDEOSDK_API_KEY:-}"
  VIDEOSDK_SECRET: "${VIDEOSDK_SECRET:-}"
  EMAIL_USER: "${EMAIL_USER:-}"
  EMAIL_PASS: "${EMAIL_PASS:-}"
  FRONTEND_URL: "${FRONTEND_URL:-}"
  CLOUDINARY_CLOUD_NAME: "${CLOUDINARY_CLOUD_NAME:-}"
  CLOUDINARY_API_KEY: "${CLOUDINARY_API_KEY:-}"
  CLOUDINARY_API_SECRET: "${CLOUDINARY_API_SECRET:-}"
  OPENAI_API_KEY: "${OPENAI_API_KEY:-}"
EOF
