apiVersion: v1
kind: ConfigMap
metadata:
  name: navi-config
  namespace: {{ include "navi.namespace" . }}
data:
  KAFKA_BROKERS: {{ printf "broker.%s.svc.cluster.local:9092" (include "navi.namespace" .) | quote }}
{{- range $k, $v := .Values.config }}
{{- if ne $k "KAFKA_BROKERS" }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
