apiVersion: v1
kind: Service
metadata:
  name: user-app
  namespace: {{ include "navi.namespace" . }}
  labels:
    app: user-app
    {{- include "navi.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: user-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
  namespace: {{ include "navi.namespace" . }}
  labels:
    app: user-app
    {{- include "navi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas.userApp }}
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - name: user-app
          image: {{ include "navi.image" (dict "root" . "name" .Values.images.userApp) }}
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: admin-app
  namespace: {{ include "navi.namespace" . }}
  labels:
    app: admin-app
    {{- include "navi.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: admin-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-app
  namespace: {{ include "navi.namespace" . }}
  labels:
    app: admin-app
    {{- include "navi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas.adminApp }}
  selector:
    matchLabels:
      app: admin-app
  template:
    metadata:
      labels:
        app: admin-app
    spec:
      containers:
        - name: admin-app
          image: {{ include "navi.image" (dict "root" . "name" .Values.images.adminApp) }}
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
