apiVersion: v1
kind: Secret
metadata:
  name: navi-secrets
  namespace: {{ include "navi.namespace" . }}
type: Opaque
stringData:
{{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
