apiVersion: v1
kind: Secret
metadata:
  name: {{ include "navi.secretName" . }}
  namespace: {{ include "navi.namespace" . }}
  labels:
    {{- include "navi.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_ACCESS_SECRET: {{ .Values.secrets.jwtAccessSecret | quote }}
  JWT_RESET_SECRET: {{ .Values.secrets.jwtResetSecret | quote }}
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  MONGO_ROOT_USER: {{ .Values.secrets.mongoRootUser | quote }}
  MONGO_ROOT_PASSWORD: {{ .Values.secrets.mongoRootPassword | quote }}
  AUTH_DATABASE_URL: {{ include "navi.authDatabaseUrl" . | quote }}
  USER_DATABASE_URL: {{ include "navi.userDatabaseUrl" . | quote }}
  CHAT_DB: {{ include "navi.chatDb" . | quote }}
  NETWORK_DB_URL: {{ include "navi.networkDbUrl" . | quote }}
  NOTIFICATION_DB_URL: {{ include "navi.notificationDbUrl" . | quote }}
  FRONTEND_ORIGIN: {{ .Values.secrets.frontendOrigin | quote }}
  OAUTH_FRONTEND_LOGIN_URL: {{ .Values.secrets.oauthFrontendLoginUrl | quote }}
  OAUTH_FRONTEND_REDIRECT_URL: {{ .Values.secrets.oauthFrontendRedirectUrl | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.googleClientId | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.googleClientSecret | quote }}
  GOOGLE_CALLBACK_URL: {{ .Values.secrets.googleCallbackUrl | quote }}
  GITHUB_CLIENT_ID: {{ .Values.secrets.githubClientId | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.secrets.githubClientSecret | quote }}
  GITHUB_CALLBACK_URL: {{ .Values.secrets.githubCallbackUrl | quote }}
  VIDEOSDK_API_KEY: {{ .Values.secrets.videosdkApiKey | quote }}
  VIDEOSDK_SECRET: {{ .Values.secrets.videosdkSecret | quote }}
  EMAIL_USER: {{ .Values.secrets.emailUser | quote }}
  EMAIL_PASS: {{ .Values.secrets.emailPass | quote }}
  FRONTEND_URL: {{ .Values.secrets.frontendUrl | quote }}
  CLOUDINARY_CLOUD_NAME: {{ .Values.secrets.cloudinaryCloudName | quote }}
  CLOUDINARY_API_KEY: {{ .Values.secrets.cloudinaryApiKey | quote }}
  CLOUDINARY_API_SECRET: {{ .Values.secrets.cloudinaryApiSecret | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
